# Generated by Django 5.1.1 on 2024-10-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_alter_homedetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_image/'),
        ),
    ]
