# Generated by Django 5.1.1 on 2024-10-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_alter_homedetails_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='property_image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='homedetails',
            name='image',
        ),
    ]
