# Generated by Django 5.1.1 on 2024-10-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_image_remove_homedetails_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='homedetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_image/'),
        ),
    ]
