# Generated by Django 5.1.1 on 2024-10-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_delete_image_homedetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='property_image/'),
        ),
        migrations.AlterField(
            model_name='homedetails',
            name='price_per_month',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
