# Generated by Django 5.1.1 on 2024-10-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_alter_homedetails_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedetails',
            name='property_type',
            field=models.TextField(null=True),
        ),
    ]
