# Generated by Django 5.1.1 on 2024-10-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_homedetails_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedetails',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homedetails',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
