# Generated by Django 5.1.1 on 2024-10-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0010_alter_homedetails_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedetails',
            name='email_id',
        ),
    ]
